name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: npm run test

      - run: npm run build -- --base-href /weather-app-angular/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/weather-app-angular/browser

      - uses: actions/deploy-pages@v4
